name: IaC AI Code Reviewer

on:
  pull_request:
    paths:
      - 'terraform/**'

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install groq

      - name: Generates Git Diff between Branches
        run: |
          git diff origin/${{ github.base_ref }}...HEAD > pr_diff.txt

      - name: Run AI Reviewer
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python app/reviewer.py